# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-02 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20200519_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('pk',)},
        ),
    ]
